## Nada Dridi

# TP1 Probabilité et statistique
<html>
   <head>
      <title>HTML Base Tag Example</title>
      <base href = "https://github.com/nevermind78/Proba_stat_4_LM" />
   </head>
   <body>
      <img src = "https://th.bing.com/th/id/OIP.Quijt6_GuJ-OzuMSNQ_S1gHaHa?pid=Api&rs=1" width="200" alt = "Logo Image"/>
    </body>

</html>


In [8]:
from __future__ import print_function
import numpy as np
import pandas as pd
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets

In [9]:
np.__version__

'1.23.3'

## Probabilités - approche fréquentiste
### Définition par la fréquence relative :
* une expérience d’ensemble fondamental  est exécutée plusieurs fois sous les mêmes conditions.
* Pour chaque événement E de , n(E) est le nombre de fois où l’événement E survient lors des n premières répétitions de l’expérience.
* **`P(E)`**, la probabilité de l’événement E est définie de la manière suivante :

$$P(E)=\lim_{n\to\infty}\dfrac{n(E)}{n} $$ 

## Simulation d'un dé parfait

In [2]:
# seed the random number generator
np.random.seed(1)

# Example: sampling 
#
# do not forget that Python arrays are zero-indexed,
# and the 2nd argument to NumPy arange must be incremented by 1
# if you want to include that value
n = 6 # les 6 faces du dé
k = 200000 # Nombre de répétition de l'éxpériance

T=np.random.choice(np.arange(1, n+1), k, replace=True)
print(T)
unique, counts = np.unique(T, return_counts=True)
print(unique,counts)
dic=dict(zip(unique, counts))
print(dic)
df=pd.DataFrame(list(dic.items()),columns=['i','Occurence'])
df.set_index(['i'], inplace=True)
df['Freq']=df['Occurence']/k
df['P({i})']='{}'.format(1/6)
df

[6 4 5 ... 6 5 2]
[1 2 3 4 5 6] [33346 33221 33447 33224 33379 33383]
{1: 33346, 2: 33221, 3: 33447, 4: 33224, 5: 33379, 6: 33383}


Occurence      Freq               P({i})
i                                          
1      33346  0.166730  0.16666666666666666
2      33221  0.166105  0.16666666666666666
3      33447  0.167235  0.16666666666666666
4      33224  0.166120  0.16666666666666666
5      33379  0.166895  0.16666666666666666
6      33383  0.166915  0.16666666666666666

In [3]:
# creation d'une liste L.
L = [1, 2, 3]

# creation d'une liste M.
M = ['a', 'b', 'c']

# la fonction zip(l1, l2) prend en parametre deux liste et retourne une serie de tuples 
# qui contient le premier element dans la premiere liste combinait avec le premier 
# element de la deuxieme liste, etc.
# puis le result est transformer en une liste grace a la fonction list().
list(zip(L, M))

[(1, 'a'), (2, 'b'), (3, 'c')]

## Ajouter de l'intéraction 

In [4]:
# une fonction qui simule le lancement d'un dés nomée dice_sim 
# qui prend k comme un parametre optionale initialiser à 100.

def dice_sim(k = 100):
    n = 6    
    
    # np.arange(1, n+1) => retourne un ndarray --> pour n = 6 np.arange(1, 6+1) => [1, 2, 3, 4, 5, 6].
    
    # k: nombre de fois on va lancer le dés.
    
    # replace = True => avec remise --> le tableaux np.arange(1, n+1) de type ndarray reste le même 
    # pour chaque iteration.
    
    # T: un ndarray contenant les normbre obtenue aprés chaque lancée.
    T = np.random.choice(np.arange(1, n+1), k, replace = True)
    
    # return_counts = True => retourne l'occurence de chaque element dans le tableux T et le sauvegarde 
    # dans le variable counts sous la forme d'un tableaux de type NDArray.
    
    # unique: contient les elements dans le tableaux T sans repetition, le type du tablequx unique est NDArray.
    
    unique, counts = np.unique(T, return_counts = True)
    
    # dic: est un dictionnaire, qui à comme clés les uniques et counts comme les valeurs de ces clés.
    
    dic = dict(zip(unique, counts)) 
    
    # df: DataFrame object, a comme colonne 'i' et 'Occurence' et a comme data la liste list(dic.items())
    # list(dic.items()) => retourne une liste contenant les occurences de tous les clés dans le 
    # dictionnaire dic.
    
    df = pd.DataFrame(list(dic.items()), columns = ['i', 'Occurence'])
    
    # remplacement de la ligne par defaut par la colonne 'i'.
    
    df.set_index(['i'], inplace = True)
    
    # l'ajout de la colonne 'Freq' avec (le valeur de chaque occurence) divisée par k (k = 100) pour 
    # obtenir la frequence.
    
    df['Freq'] = df['Occurence'] / k
    
    # l'ajout de la colonne P(i) qui comme valeur la probabilitée d'obtenir un nombre aleatoire compris
    # entre 1 et 6.
    
    df['P({i})'] = '{0:.3f}'.format(1 / 6)
    
    # retourne un DataFrame object
    return df
    

In [5]:
# simulation du le lancement d'un dés 100 fois

dice_sim(100)

Occurence  Freq P({i})
i                        
1         19  0.19  0.167
2         16  0.16  0.167
3         17  0.17  0.167
4         15  0.15  0.167
5         15  0.15  0.167
6         18  0.18  0.167

In [6]:
# la fonction interact permet de modifier les valeurs de k et obtenir imediatement une resultat

interact(dice_sim ,k = widgets.IntSlider(min=1000, max=50000, step=500, value=10))

interactive(children=(IntSlider(value=1000, description='k', max=50000, min=1000, step=500), Output()), _dom_c…

<function __main__.dice_sim(k=100)>

## Cas d'un dé truqué

In [2]:
# p: liste des probabilitées

p = [0.1, 0.1, 0.1, 0.1,0.1,0.5]

# sum(p) => retourne la somme des elements dans p
sum(p)

1.0

In [3]:
# une fonction qui simule le lancement d'un dés nomée dice_sim 
# qui prend k et q comme deux parametres optionales avec k 
# initialiser à 100 et q initialiser à [[0.1, 0.1, 0.1, 0.1,0.1,0.5], [0.2, 0.1, 0.2, 0.1,0.1,0.3]] .

def dice_sim(k = 100, q = [[0.1, 0.1, 0.1, 0.1,0.1,0.5], [0.2, 0.1, 0.2, 0.1,0.1,0.3]]):
    n = 6
    
    # qq: une liste egale à [[0.1, 0.1, 0.1, 0.1,0.1,0.5], [0.2, 0.1, 0.2, 0.1,0.1,0.3]]
    
    qq = q
    
    # np.arange(1, n+1) => retourne un ndarray --> pour n = 6 np.arange(1, 6+1) => [1, 2, 3, 4, 5, 6].
    
    # k: nombre de fois on va lancer le dés.
    
    # replace = True => avec remise --> le tableaux np.arange(1, n+1) de type ndarray reste le même 
    # pour chaque iteration.
    
    T = np.random.choice(np.arange(1, n+1), k, replace = True,p = qq)
    
    # return_counts = True => retourne l'occurence de chaque element dans le tableux T et le sauvegarde 
    # dans le variable counts sous la forme d'un tableaux de type NDArray.
    
    # unique: contient les elements dans le tableaux T sans repetition, le type du tablequx unique est NDArray.
    
    unique, counts = np.unique(T, return_counts = True)
    
    # dic: est un dictionnaire, qui à comme clés les uniques et counts comme les valeurs de ces clés.
    
    dic = dict(zip(unique, counts))
    
    # df: DataFrame object, a comme colonne 'i' et 'Occurence' et a comme data list(dic.items())
    
    # list(dic.items()) => retourne une liste contenant les occurences de tous les clés dans le 
    # dictionnaire dic.
    
    df = pd.DataFrame(list(dic.items()), columns = ['i', 'Occurence'])
    
    # remplacement de la ligne par defaut par la colonne 'i'.
    
    df.set_index(['i'], inplace = True)
    
    # l'ajout de la colonne 'Freq' avec (le valeur de chaque occurence) divisée par k (k = 100) pour 
    # obtenir la frequence.
    
    df['Freq'] = df['Occurence'] / k
    
    # l'ajout de la colonne P(i) qui comme valeur la probabilitée d'obtenir un nombre aleatoire compris
    # entre 1 et 6.
    
    df['P({i})'] = ['{0:.3f}'.format(j) for j in q]
    
    # retourne un DataFrame object
    return df

In [10]:
# la fonction interact permet de modifier les valeurs de k et de q et obtenir imediatement une resultat

interact(dice_sim, k = widgets.IntSlider(min=1000, max=50000, step=500, value=10))

interactive(children=(IntSlider(value=1000, description='k', max=50000, min=1000, step=500), Dropdown(descript…

<function __main__.dice_sim(k=100, q=[[0.1, 0.1, 0.1, 0.1, 0.1, 0.5], [0.2, 0.1, 0.2, 0.1, 0.1, 0.3]])>

## Exercice 1: 

Tester l'intéraction précédente pour plusieurs valeurs de `q`
Donner votre conclusion :

In [9]:
##on constate que l'occurence le plus élevée est de la face(1,2,3,4,5,6) ayyant la plus grande probabilité 
### et quand la probabilité dminue, le frequence diminue aussi 

#cest à cause de dé truqé ( non parfait)



## Permutation Aléatoire

In [10]:
np.random.seed(2)

m = 1
n = 10

v = np.arange(m, n+1)
print('v =', v)

np.random.shuffle(v)
print('v, shuffled =', v)

v = [ 1  2  3  4  5  6  7  8  9 10]
v, shuffled = [ 5  2  6  1  8  3  4  7 10  9]


## Exercice 2
Vérifier que les permutation aléatoires sont uniforme , c'est à dire que la probabilité de générer une permutation d'élement de {1,2,3} est 1/6.
En effet les permutations de {1,2,3} sont :
* 1 2 3
* 1 3 2
* 2 1 3
* 2 3 1
* 3 1 2
* 3 2 1


In [11]:
k =10
m = 1
n = 3
v = np.arange(m, n+1)
T=[]
for i in range(k):
    np.random.shuffle(v)
    w=np.copy(v)
    T.append(w)

In [12]:
TT=[str(i) for i in  T]
TT

['[1 3 2]',
 '[3 1 2]',
 '[1 2 3]',
 '[1 3 2]',
 '[3 1 2]',
 '[3 1 2]',
 '[1 3 2]',
 '[2 1 3]',
 '[3 1 2]',
 '[2 3 1]']

In [13]:
k =1000
m = 1
n = 3
v = np.arange(m, n+1)
T=[]
for i in range(k):
    np.random.shuffle(v)
    w=np.copy(v)
    T.append(w)

TT=[str(i) for i in  T]
unique, counts = np.unique(TT, return_counts=True)
dic=dict(zip(unique, counts))
df=pd.DataFrame(list(dic.items()),columns=['i','Occurence'])
df.set_index(['i'], inplace=True)
df['Freq']=df['Occurence']/k
df['P({i,j,k})']='{0:.3f}'.format(1/6)
df

Occurence   Freq P({i,j,k})
i                                   
[1 2 3]        169  0.169      0.167
[1 3 2]        180  0.180      0.167
[2 1 3]        161  0.161      0.167
[2 3 1]        169  0.169      0.167
[3 1 2]        157  0.157      0.167
[3 2 1]        164  0.164      0.167

### Donner  votre conclusion en expliquant le script 

In [14]:
## Explication 
### je vais explquée le script par lexplication des ligne de code :
### v = np.arange(m, n+1) : va crée 3 variables (1,2 et 3)
### np.random.shuffle(v)  :cet ligne faire la permutation entre les positions des  trois variables
### for i in range(k):
###  np.random.shuffle(v)
###  w=np.copy(v)
###  T.append(w)
### ce boucle faire changer les positions des trois variables k(1000) fois et ajouter à chaque fois 
### la résultat obtenue à la liste T 
### TT=[str(i) for i in  T] :liste comprehension : convertir chaque liste (qui corresopnd ala comteur i dans chaque iteration)
### pour une chaine de caractères (string)

### les lignes restants sont chargée d'organiser et calculer  et de formater le resultat,  sous format du tableau si-dessus

## Probabilité conditionnelle 

Rappelons que l'interprétation fréquentiste de la probabilité conditionnelle basée sur un grand nombre `n` de répétitions d'une expérience est $ P (A | B) ≈ n_ {AB} / n_ {B} $, où $ n_ {AB} $ est le nombre de fois où $ A \cap B $ se produit et $ n_ {B} $ est le nombre de fois où $ B $ se produit. Essayons cela par simulation et vérifions les résultats de l'exemple 2.2.5. Utilisons donc [`numpy.random.choice`] (https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.choice.html) pour simuler les familles` n`, chacun avec deux enfants.


In [15]:
np.random.seed(34)

n = 10**5
child1 = np.random.choice([1,2], n, replace=True) 
child2 = np.random.choice([1,2], n, replace=True) 

print('child1:\n{}\n'.format(child1))

print('child2:\n{}\n'.format(child2))

child1:
[2 1 1 ... 1 2 1]

child2:
[2 2 2 ... 2 2 1]



Ici, «child1» est un «tableau NumPy» de longueur «n», où chaque élément est un 1 ou un 2. En laissant 1 pour «fille» et 2 pour «garçon», ce «tableau» représente le sexe du enfant aîné dans chacune des familles «n». De même, «enfant2» représente le sexe du plus jeune enfant de chaque famille.


In [16]:
np.random.choice(["girl", "boy"], n, replace=True)

array(['boy', 'boy', 'boy', ..., 'boy', 'boy', 'boy'], dtype='<U4')

mais il est plus pratique de travailler avec des valeurs numériques.

Soit $ A $ l'événement où les deux enfants sont des filles et $ B $ l'événement où l'aîné est une fille. Suivant l'interprétation fréquentiste, nous comptons le nombre de répétitions où $ B $ s'est produit et le nommons `n_b`, et nous comptons également le nombre de répétitions où $ A \cap B $ s'est produit et le nommons` n_ab`. Enfin, nous divisons `n_ab` par` n_b` pour approximer $ P (A | B) $.

In [17]:
n_b = np.sum(child1==1)
n_ab = np.sum((child1==1) & (child2==1))

print('P(both girls | elder is girl) = {:0.2F}'.format(n_ab / n_b))

P(both girls | elder is girl) = 0.50


L'esperluette `&` est un élément par élément $ AND $, donc `n_ab` est le nombre de familles où le premier et le deuxième enfant sont des filles. Lorsque nous avons exécuté ce code, nous avons obtenu 0,50, confirmant notre réponse $ P (\text {les deux filles | l'aîné est une fille}) = 1/2 $.

Soit maintenant $ A $ l'événement où les deux enfants sont des filles et $ B $ l'événement selon lequel au moins l'un des enfants est une fille. Alors $ A \cap B $ est le même, mais `n_b` doit compter le nombre de familles où au moins un enfant est une fille. Ceci est accompli avec l'opérateur élémentaire $ OR $ `|` (ce n'est pas une barre de conditionnement; c'est un $ OR $ inclusif, retournant `True` si au moins un élément est` True`).

In [18]:
n_b = np.sum((child1==1) | (child2==2))
n_ab = np.sum((child1==1) & (child2==1))

print('P(both girls | at least one girl) = {:0.2F}'.format(n_ab / n_b))

P(both girls | at least one girl) = 0.33


Pour nous, le résultat était de 0,33, confirmant que $ P (\text {les deux filles | au moins une fille}) = 1/3 $.